// Code generated by "stringer -type ErrorType"; DO NOT EDIT.

package kvdb

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[DatabaseNameOutOfBounds-1]
	_ = x[DatabaseStateInvalid-2]
	_ = x[DatabaseKeyExists-3]
	_ = x[DatabaseKeyNotPresent-4]
}

const _ErrorType_name = "DatabaseNameOutOfBoundsDatabaseStateInvalidDatabaseKeyExistsDatabaseKeyNotPresent"

var _ErrorType_index = [...]uint8{0, 23, 43, 60, 81}

func (i ErrorType) String() string {
	i -= 1
	if i >= ErrorType(len(_ErrorType_index)-1) {
		return "ErrorType(" + strconv.FormatInt(int64(i+1), 10) + ")"
	}
	return _ErrorType_name[_ErrorType_index[i]:_ErrorType_index[i+1]]
}
