// Code generated by "stringer -type ErrorType"; DO NOT EDIT.

package kvdb

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Database_State_Invalid-1]
}

const _ErrorType_name = "Database_State_Invalid"

var _ErrorType_index = [...]uint8{0, 22}

func (i ErrorType) String() string {
	i -= 1
	if i >= ErrorType(len(_ErrorType_index)-1) {
		return "ErrorType(" + strconv.FormatInt(int64(i+1), 10) + ")"
	}
	return _ErrorType_name[_ErrorType_index[i]:_ErrorType_index[i+1]]
}
