// Code generated by "stringer -type Filemode"; DO NOT EDIT.

package kvdb

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Mode_Read-1]
	_ = x[Mode_Write-2]
	_ = x[Mode_ReadWrite-3]
}

const _Filemode_name = "Mode_ReadMode_WriteMode_ReadWrite"

var _Filemode_index = [...]uint8{0, 9, 19, 33}

func (i Filemode) String() string {
	i -= 1
	if i >= Filemode(len(_Filemode_index)-1) {
		return "Filemode(" + strconv.FormatInt(int64(i+1), 10) + ")"
	}
	return _Filemode_name[_Filemode_index[i]:_Filemode_index[i+1]]
}
